# Generated by Django 5.0 on 2024-01-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intarnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
